import { useState } from 'react';
import axios from 'axios';
import VenueCard from './VenueCard';

const api = axios.create({ baseURL: '/api' });
api.interceptors.request.use((config) => { const token = localStorage.getItem('anom_token'); if (token) config.headers.Authorization = `Bearer ${token}`; return config; });
const venueTypes = ['Coffee Shops', 'Restaurants', 'Parks', 'Libraries'];

export default function MeetingSuggestion({ matches, onSelect }) {
  const [matchId, setMatchId] = useState(''); const [city, setCity] = useState(''); const [venues, setVenues] = useState([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const chooseMatch = (event) => { const id = event.target.value; setMatchId(id); const match = matches.find((item) => item.profile?.id === id); if (match?.profile?.city) setCity(match.profile.city); };
  const mapSearch = (type) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${type} near ${city}`)}`;
  const generate = async () => { setLoading(true); setError(''); try { const response = await api.post('/ai/meeting-suggestion', { matchId, city, interests: [] }); setVenues(response.data.venues || []); } catch (err) { setError(err.response?.data?.message || 'Could not generate venue suggestions.'); } finally { setLoading(false); } };
  return <section className="mt-6 rounded-3xl bg-gradient-to-br from-indigo-50 via-white to-violet-50 p-5 ring-1 ring-indigo-100 sm:p-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-indigo-600">Google Maps venue suggestions</p><h2 className="mt-1 text-xl font-bold text-slate-900">Find a comfortable place to meet</h2><p className="mt-1 text-sm text-slate-600">Explore nearby coffee shops, restaurants, parks, and libraries, then select a venue for your request.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><select value={matchId} onChange={chooseMatch} className="rounded-xl border border-slate-200 bg-white p-3 text-sm"><option value="">Choose a match</option>{matches.map((match) => <option key={match.profile?.id} value={match.profile?.id}>{match.profile?.name}</option>)}</select><input value={city} onChange={(event) => setCity(event.target.value)} placeholder="City" className="rounded-xl border border-slate-200 bg-white p-3 text-sm"/><button disabled={!matchId || !city || loading} onClick={generate} className="rounded-xl bg-indigo-600 px-4 py-3 text-sm font-semibold text-white hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-50">{loading ? 'Finding venues…' : 'Get AI suggestions'}</button></div>{city && <div className="mt-4 flex flex-wrap gap-2">{venueTypes.map((type) => <a key={type} href={mapSearch(type)} target="_blank" rel="noreferrer" className="rounded-full bg-white px-3 py-2 text-xs font-semibold text-indigo-700 ring-1 ring-indigo-100 hover:bg-indigo-100">Open {type} in Maps ↗</a>)}</div>}{error && <p className="mt-3 text-sm text-red-600">{error} <button onClick={generate} className="font-semibold underline">Retry</button></p>}{loading && <div className="mt-5 grid gap-3 sm:grid-cols-2">{[1, 2, 3, 4].map((item) => <div key={item} className="h-32 animate-pulse rounded-2xl bg-white/70" />)}</div>}{venues.length > 0 && <div className="mt-5 grid gap-3 sm:grid-cols-2">{venues.map((venue, index) => <VenueCard key={`${venue.name}-${index}`} venue={venue} onSelect={onSelect} />)}</div>}</section>;
}
